### ISSUE TITLE
[Linux] Armory crash on blockchain loading

### ISSUE THREAD

**Issue by blob42** [etotheipi/BitcoinArmory#223]
Since I updated armory to 0.92 I started having random crashes on startup. 
With the last updated armory always crashes just before loding the blockchain (after the sync). I tried every reset possible, and also with a new blockchain. 

Bitcoin core is the latest version: 0.9.2.1

The only thing I didn't try is emptying the .armory dir in fear of losing my wallet
EDIT: Same thing with 0.92.1

Here's the crash log from armory: 

TypeError: in method 'BlockDataManager_LevelDB_SetBlkFileLocation', argument 2 of type 'string'
2014-07-31 23:29 (INFO) -- Networking.py:152 - Received version message from peer:
2014-07-31 23:29 (INFO) -- Networking.py:153 -    Version:     70002
2014-07-31 23:29 (INFO) -- Networking.py:154 -    SubVersion:  /Satoshi:0.9.2.1/
2014-07-31 23:29 (INFO) -- Networking.py:155 -    TimeStamp:   1406842165
2014-07-31 23:29 (INFO) -- Networking.py:156 -    StartHeight: 313381
2014-07-31 23:29 (INFO) -- Networking.py:348 - Handshake finished, connection open!
2014-07-31 23:29 (INFO) -- ArmoryQt.py:5886 - Starting load blockchain
2014-07-31 23:29 (INFO) -- ArmoryQt.py:2036 - loadBlockchainIfNecessary
2014-07-31 23:29 (ERROR) -- ArmoryQt.py:915 - 29 attempts to load blockchain failed.  Remove mempool.bin.
2014-07-31 23:29 (ERROR) -- ArmoryQt.py:920 - File mempool.bin does not exist. Nothing deleted.
2014-07-31 23:29 (INFO) -- ArmoryQt.py:2082 - Setting netmode: 1
2014-07-31 23:29 (INFO) -- BDM.py:431 - Setting online mode: True (wait=False)
2014-07-31 23:29 (INFO) -- BDM.py:1358 - Go online requested
2014-07-31 23:29 (INFO) -- BDM.py:915 - Setting Armory Home Dir: /home/spike/.armory/
2014-07-31 23:29 (INFO) -- BDM.py:916 - Setting BlkFile Dir:     /media/spike/DATA/bitcoin-data/blocks
2014-07-31 23:29 (INFO) -- BDM.py:917 - Setting LevelDB Dir:     /home/spike/.armory/databases
2014-07-31 23:29 (INFO) -- Networking.py:63 - Connection initiated.  Start handshake
2014-07-31 23:29 (ERROR) -- BDM.py:1383 - Error processing BDM input
2014-07-31 23:29 (ERROR) -- BDM.py:1385 - Received inputTuple: GoOnlineRequested [13, 81052294, False]
2014-07-31 23:29 (ERROR) -- BDM.py:1386 - Error processing ID (81052294)
2014-07-31 23:29 (ERROR) -- BDM.py:1387 - ERROR:
Traceback (most recent call last):
  File "/usr/lib/armory/armoryengine/BDM.py", line 1369, in run
    self.__startLoadBlockchain()
  File "/usr/lib/armory/armoryengine/Timer.py", line 99, in inner
    ret = func(_args, *_kwargs)
  File "/usr/lib/armory/armoryengine/BDM.py", line 921, in __startLoadBlockchain
    self.bdm.SetBlkFileLocation(blockdir)
  File "/usr/lib/armory/CppBlockUtils.py", line 1791, in SetBlkFileLocation
    def SetBlkFileLocation(self, *args): return _CppBlockUtils.BlockDataManager_LevelDB_SetBlkFileLocation(self, *args)
TypeError: in method 'BlockDataManager_LevelDB_SetBlkFileLocation', argument 2 of type 'string'
2014-07-31 23:29 (INFO) -- Networking.py:152 - Received version message from peer:
2014-07-31 23:29 (INFO) -- Networking.py:153 -    Version:     70002
2014-07-31 23:29 (INFO) -- Networking.py:154 -    SubVersion:  /Satoshi:0.9.2.1/
2014-07-31 23:29 (INFO) -- Networking.py:155 -    TimeStamp:   1406842166
2014-07-31 23:29 (INFO) -- Networking.py:156 -    StartHeight: 313381
2014-07-31 23:29 (INFO) -- Networking.py:348 - Handshake finished, connection open!

**Comment by fresheneesz** [comment]
I'm seeing this same problem after following these instructions on windows: https://support.bitcoinarmory.com/kb/article/16-change-or-move-the-blockchain-database-storage-location-for-armory-and-bitcoin-core

I already have a --satoshi-datadir flag in my shortcut that I added as per the instructions in that link. What could be going wrong here?

**Comment by Douglas1949** [comment]
I have the same problem but clearly am not as tech-savy as you - how do I "launch armory with --satoshi-datadir"?
Thanks
Douglas
