### ISSUE TITLE
[0.92.99.3] Cannot Cancel or Close Transaction Window and Unconfirmed Funds

### ISSUE THREAD

**Issue by zs9099** [etotheipi/BitcoinArmory#261]
Hello, Bitcointalk is down, so I figured I'd make a new issue here.

Once I open the transaction window, it will not let me close it and there is no cancel button.
I'm not sure if it's like that on purpose, but sometimes it can get annoying because I either have to execute the transaction or quit Armory completely.

I also noticed that Armory now displays unconfirmed funds in Spendable Funds. However I try to send funds, the Send button does nothing and displays this error in the log each time I click it:

2015-01-22 06:45 (ERROR) -- Traceback (most recent call last):
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ui/TxFrames.py", line 757, in createTxAndBroadcast
    ustx = self.validateInputsGetUSTX()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ui/TxFrames.py", line 597, in validateInputsGetUSTX
    utxoList = self.getUsableTxOutList(totalSend)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ui/TxFrames.py", line 828, in getUsableTxOutList
    return list(self.wlt.getUTXOListForSpendVal(totalSend))
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/PyBtcWallet.py", line 52, in inner
    return func(*args, **kwargs)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/PyBtcWallet.py", line 451, in getUTXOListForSpendVal
    return self.cppWallet.getSpendableTxOutListForValue(valToSpend, IGNOREZC);
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/CppBlockUtils.py", line 1806, in getSpendableTxOutListForValue
    def getSpendableTxOutListForValue(self, *args): return _CppBlockUtils.BtcWallet_getSpendableTxOutListForValue(self, *args)
RuntimeError

I'd also like a Cancel button on the Send Bitcoins dialog so I don't have to close Armory each time I accidentally open it.

I am on Mac OS X 10.10 using testing version 0.92.99.3

**Comment by zs9099** [comment]
Reported on bitcointalk
