### ISSUE TITLE
[0.92.99.3] Unable to Sign Transactions to and from Lockboxes

### ISSUE THREAD

**Issue by zs9099** [etotheipi/BitcoinArmory#262]
Bitcointalk is down again

2015-01-24 15:47 (ERROR) -- Traceback (most recent call last):
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ui/MultiSigDialogs.py", line 2712, in doSign
    self.doSignForInput(idstring, nIdx)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ui/MultiSigDialogs.py", line 2932, in doSignForInput
    ustxi.createAndInsertSignature(pytx, addrObj.binPrivKey32_Plain)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/Transaction.py", line 1276, in createAndInsertSignature
    derSig = self.createTxSignature(pytx, sbdPrivKey, hashcode, DetSign)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/Transaction.py", line 1235, in createTxSignature
    raise SignatureError('No PubKey that matches this privKey')
SignatureError: No PubKey that matches this privKey

That repeated itself in logs about 6 times before I was actually able to sign it by clicking the Sign button right after the passphrase text field closed.

**Comment by zs9099** [comment]
Reported on bitcointalk
