### ISSUE TITLE
Stuck "Initializing Bitcoin Engine"

### ISSUE THREAD

**Issue by yuvadm** [etotheipi/BitcoinArmory#268]
New install of Armory, downloaded the entireblock chain, but still stuck on "Initializing Bitcoin Engine". This error shows up in the logs everytime Armory is launched:

```
2015-03-12 22:27 (ERROR) -- Traceback (most recent call last):
  File "/opt/BitcoinArmory/ArmoryQt.py", line 7038, in method_signal
    method()
  File "/opt/BitcoinArmory/ArmoryQt.py", line 2473, in proceedOnceBitcoindIsReady
    self.loadBlockchainIfNecessary()
  File "/opt/BitcoinArmory/ArmoryQt.py", line 2525, in loadBlockchainIfNecessary
    TheBDM.goOnline()
  File "/opt/BitcoinArmory/armoryengine/BDM.py", line 148, in inner
    return func(*newArgs, **kwargs)
  File "/opt/BitcoinArmory/armoryengine/BDM.py", line 251, in goOnline
    self.bdmThread.setConfig(self.bdmConfig())
  File "/opt/BitcoinArmory/armoryengine/BDM.py", line 148, in inner
    return func(*newArgs, **kwargs)
  File "/opt/BitcoinArmory/armoryengine/BDM.py", line 339, in bdmConfig
    bdmConfig.blkFileLocation = blockdir
  File "/opt/BitcoinArmory/CppBlockUtils.py", line 4219, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlockDataManagerConfig, name, value)
  File "/opt/BitcoinArmory/CppBlockUtils.py", line 51, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/opt/BitcoinArmory/CppBlockUtils.py", line 43, in _swig_setattr_nondynamic
    return method(self, value)
TypeError: in method 'BlockDataManagerConfig_blkFileLocation_set', argument 2 of type 'string const &'
```

Running Arch x86_64, Bitcoin 0.10.0, Armory 0.93.

**Comment by yuvadm** [comment]
Duplicate of #223 , weird it didn't show up when I searched for it. Solved with:

```bash
$ armory --satoshi-datadir=/path/to/dir
```
