### ISSUE TITLE
python-2.7 errors

### ISSUE THREAD

**Issue by yurivict** [etotheipi/BitcoinArmory#278]
0.93.1 breaks with python python27-2.7.9, see error log below.
I am seeing this on FreeBSD, but the last error also googles for linux:
https://www.google.com/?gws_rd=ssl#q=%22exceptions.NameError:+global+name+%27reactor%27+is+not+defined%22
This last error causes armory to freeze on BSD.
Requirement says that it works with Python 2.6/2.7

@njaard sorry for bothering you, but maybe you know what the matter is, because I think you made this release 12 days ago.

---errors---
/usr/local/lib/armory/armoryengine/Transaction.py:2675: SyntaxWarning: import * only allowed at module level
  def PyCreateAndSignTx_old(srcTxOuts, dstAddrsVals):
(ERROR) announcefetch.py:285 - Specified URL was inaccessible
(ERROR) announcefetch.py:286 - Tried: https://bitcoinarmory.com/announce.txt?osvar=freebsd&os=bsd&ver=0.93.1&id=38b6dd78
(ERROR) announcefetch.py:285 - Specified URL was inaccessible
(ERROR) announcefetch.py:286 - Tried: https://s3.amazonaws.com/bitcoinarmory-media/announce.txt
(WARNING) announcefetch.py:299 - Error fetching announce digest
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/armory/qtdefines.py", line 609, in MsgBoxWithDNAA
    result = dlg.exec_()
  File "/usr/local/lib/armory/qtdefines.py", line 58, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/armory/qtdefines.py", line 768, in exec_
    return super(ArmoryDialog, self).exec_()
  File "/usr/local/lib/armory/qt4reactor.py", line 231, in _iterate
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/armory/ArmoryQt.py", line 6533, in Heartbeat
    reactor.callLater(nextBeatSec, self.Heartbeat)
exceptions.NameError: global name 'reactor' is not defined

**Comment by droark** [comment]
Hi. Sorry about taking awhile to reply. Thanks for the report. I've seen this and will look into it.

**Comment by yurivict** [comment]
No problem!

This bug is a killer for armory on BSD. Python version on FreeBSD is very clean, pretty much everything works, but not armory. This makes me believe that these are real syntax errors. Users actually contacted me about it, but I can't do anything because of this broken release.

**Comment by droark** [comment]
Hello. After investigating further, I can't seem to reproduce this. I'm not sure why this would happen. Maybe Twisted isn't installed?

Regarding Python 2.6/2.7, I believe this is outdated. I remember that 2.6 was at least temporarily dropped due to a code issue that had no valid workarounds for 2.6. I don't know offhand if this is still the case.

**Comment by yurivict** [comment]
py27-twistedCore-15.0.0_1 is installed.
python 2.7 seems to work fine for everybody.

**Comment by droark** [comment]
Thanks. Can you confirm that people seeing this issue are on 2.6?

**Comment by yurivict** [comment]
I only have 2.7 here. Many dependent packages are py27  dependent ad have this prefix.
I am not sure how to roll back to py26

**Comment by yurivict** [comment]
I did some more troubleshooting, and found that the above errors happen in relation with the wallet upgrade. It comes up and claims the wallet is in old format, etc, and they happen.

With the brand new wallet there is only one error in armoryengine/Transaction.py, it doesn't like this line be in the middle of the function:
````
from armoryengine.MultiSigUtils import *
````
I moved it to the top. You may want to patch this.

Anther problem is that without ~/.bitcoin directory there is this failure:
````
Log file doesn't exist [yet]
(ERROR) ArmoryUtils.py:1187 - Error getting system details:
Traceback (most recent call last):
  File "/usr/local/lib/armory/armoryengine/ArmoryUtils.py", line 1185, in <module>
    SystemSpecs = GetSystemDetails()
  File "/usr/local/lib/armory/armoryengine/ArmoryUtils.py", line 1180, in GetSystemDetails
    out.HddAvailB = getHddSize(BTC_HOME_DIR)    / (1024**3)
  File "/usr/local/lib/armory/armoryengine/ArmoryUtils.py", line 1177, in getHddSize
    s = os.statvfs(adir)
OSError: [Errno 2] No such file or directory: '/home/yuri/.bitcoin/'
````
Armory shouldn't call getHddSize on the missing ~/.bitcoin, better create it first.

Another (minor) problem is that armory fails to fetch data through with torrent. I couldn't figure out why. Can you give me a hint what might be missing?

So the wallet upgrade procedure caused the errors in my OP.

**Comment by goatpig** [comment]
We do not support Python 2.6 nor FreeBSD. If you are going to use an unsupported OS, we recommend you do not use bitcoind auto-management and force your paths with the --satoshi-datadir and --datadir command line arguments. 

We do not guarantee automated downloading, process management and path detection will work on unsupported OS, nor do we test our software on these platforms.

**Comment by yurivict** [comment]
I maintain FreeBSD port. And the questions I asked are about python-2.7, not 2.6.
It actually works fine. Except for the mentioned python errors.

**Comment by goatpig** [comment]
Then you should disable bitcoind auto management in your releases. 

As for the other issues:

1) Armory should not create Core folders, Core should. GetSystemDetails() throws on errors and is called from a try block, this is proper behavior.

2) I don't understand what you mean by upgrading wallets. All existing Armory wallet formats are supported by the current version (0.93.x). There is no path to upgrade from one version to another, you would have create a new wallet and move the coins yourself. Please elaborate.

3) Torrent downloader is probably broken due to some internal working of the library we use. Afaik this is the case on OSX too. You should take that to the library maintainer. We use it as is so I don't expect it is an issue on our side, unless it is feeding bogus paths to the lib. 

You should force your paths through command line arguments rather than let Armory auto detect them until your setup is stable.

**Comment by yurivict** [comment]
> 2) I don't understand what you mean by upgrading wallets.

0.93.1 was asking some question about wallet upgrade (Yes/No), and was breaking afterwards. But now I am not seeing this any more. Now I am not sure what was that.

> 3) Torrent downloader is probably broken ...

I asked library maintainers.

> You should force your paths through command line arguments

This is already done, and Armory works on FreeBSD pretty ok now.

Maybe you could create blank URLs for OS=freebsd, so that they at least wouldn't print errors all the time? For example:
https://bitcoinarmory.com/announce.txt?osvar=freebsd&os=bsd&ver=0.93.1&id=38b6dd78

**Comment by Rudd-O** [comment]
The traceback is a really dumb fuckup in ArmoryQt.py.

Here is the fix:

```
diff --git a/ArmoryQt.py b/ArmoryQt.py
index 2765c59..7d3a9f8 100755
--- a/ArmoryQt.py
+++ b/ArmoryQt.py
@@ -6381,6 +6381,7 @@ class ArmoryMainWindow(QMainWindow):
       run every second, or whatever is specified in the nextBeatSec
       argument.
       """
+      from twisted.internet import reactor

       # Special heartbeat functions are for special windows that may need
       # to update every, say, every 0.1s
```

**Comment by Rudd-O** [comment]
Please fix the spaghetti code, dude, including all of the `*` imports.  Come on, this application exists to manage money.  Is this code even tested?

https://github.com/etotheipi/BitcoinArmory/pull/320
