### ISSUE TITLE
Invalid signature when preparing lockbox TX

### ISSUE THREAD

**Issue by yuvadm** [etotheipi/BitcoinArmory#291]
Erratically, a lockbox can enter a weird (corrupt?) state where broadcasting fully-signed transactions is impossible. Clicking `Broadcast` does nothing, and the following error is thrown to stdout/err:

```
(ERROR) Transaction.py:1363 - Signature in USTXI is not valid
(ERROR) Transaction.py:2445 - Attempted to prepare final tx, but not all sigs available
(ERROR) Traceback (most recent call last):
  File "/opt/BitcoinArmory/ui/MultiSigDialogs.py", line 3093, in doBroadcast
    finalTx = self.ustx.getSignedPyTx(doVerifySigs=True)
  File "/opt/BitcoinArmory/armoryengine/Transaction.py", line 2446, in getSignedPyTx
    raise SignatureError('Invalid signature while preparing final tx')
SignatureError: Invalid signature while preparing final tx

Traceback (most recent call last):
  File "/opt/BitcoinArmory/ui/MultiSigDialogs.py", line 3093, in doBroadcast
    finalTx = self.ustx.getSignedPyTx(doVerifySigs=True)
  File "/opt/BitcoinArmory/armoryengine/Transaction.py", line 2446, in getSignedPyTx
    raise SignatureError('Invalid signature while preparing final tx')
armoryengine.ArmoryUtils.SignatureError: Invalid signature while preparing final tx
```

Previously the lockbox has successfully created transactions, and nothing in the signing process has been out of the ordinary. This behavior has been noticed on two separate occasions with two different wallets+lockboxes.

Armory 0.93.1 on fully updated Arch x86_64.

**Comment by etotheipi** [comment]
Hi yuvadm,

We've heard of this issue occurring very sporadically, but have not been able to reproduce it ourselves.  Would you be willing to send us the signed transaction text block so we can examine it for irregularities?  We understand if you don't want to for privacy reasons.  Either way, can you please report this through our support channel, and if you are willing to share the transaction data, please attach it to the ticket:

https://support.bitcoinarmory.com/home

Thanks for being patient.

**Comment by yuvadm** [comment]
@etotheipi let me know how to extract the data, and I'll happily send over the block.

**Comment by etotheipi** [comment]
We just want to see the chunk of data that you sent between computers to collect signatures.  It always shows up as a block of text to be copy & pasted between systems or saved as a file.  We would like to see the one that has all the signatures just before you broadcast it.

**Comment by yuvadm** [comment]
Oh, of course, we should have those

**Comment by yuvadm** [comment]
@etotheipi I have an environment where I consistently get failed signatures. Let's try to escalate this, I have plenty of data to share.

**Comment by etotheipi** [comment]
Awesome.  Maybe we'll finally nail this thing.    Did you submit one of the "invalid" transactions through our support system? (I don't have access to it at the moment to check).

What OS are you on?  If you are on Linux then it can be pretty easy to get you some slightly modified code that helps debug it.   Or is your consistent environment with paper backup data that you can share with us?

**Comment by yuvadm** [comment]
Yes, I believe there are two open tickets with logs. I'm on Linux, let me know what I can do to get you more meaningful information. I'll be happy to share anything that doesn't contain private key material.

**Comment by AndyOfiesh** [comment]
In case you didn't see my response on the support channel. Please post all of your signature text blocks. They do not appear in the logs.

**Comment by AndyOfiesh** [comment]
Also, I think you should try signing your transaction with an offline 0.92.3 instance.

**Comment by etotheipi** [comment]
To be clear, please attach the "TXSIGCOLLECT" block of text to the support ticket, not just the log files.  Please don't post it here.

**Comment by yuvadm** [comment]
Added 3 files to the ticket

**Comment by AndyOfiesh** [comment]
Thanks for the files. I am debugging now. These files will be very useful.

**Comment by etotheipi** [comment]
Hi yuvadm,

We're actively investigating this problem.  I appreciate you being patient with us.  There are two distinct things going on here:

1. Your original report suggested the when attempting to broadcast the signed tx, you got the following error:

    armoryengine.ArmoryUtils.SignatureError: Invalid signature while preparing final tx

However, I got through transaction verification without that error on one of the signed transactions (TXSIGCOLLECT) blocks you submitted over the support channel.  Did you submit a transaction that triggers that error on your side?   Are you instead seeing "It appears the transaction was not accepted by the network"?

2.  However, even in the absence of the above problem, another problem popped up:  the fee is insufficient for your transaction size.  Even if your transaction got through the signature checks, it fails to be accepted by the network due to having insufficient fee.  The fee you put on tx is 0.0001, which is sufficient for most transactions, but not yours which is rather large.

The real issue is on our side, though you can manually solve the "Tx not accepted error" by manually increasing the fee.  Armory has logic that detects when a fee higher than 0.0001 is required, but it seems to be failing for lockbox transactions.  If you do this with a regular single-sig offline transaction, it will not let you proceed with an insufficient fee.  However, it seems this logic doesn't work for lockbox transactions.

A fee of 0.01 should *always* work.  It might be 0.001 (the fee rules have changed since I last looked).  If it's not too much trouble to get all the signatures, I would try 0.001 first, then 0.01.  However, if you get the "Invalid signature" error when attempting to broadcast, that's not a fee issue, and you should send that over the support channel so we can debug that as a separate problem.

Thanks for being patient.

**Comment by yuvadm** [comment]
@etotheipi thanks for the heads up on the fee issue! In any case one of the files should be one where the signature is invalid. If that's not the case I'll make sure you get a file that does reproduce that behavior.

**Comment by etotheipi** [comment]
Great news: we finally nailed this bug!  It affects 1-out-of-512 signatures due to a signature padding error.     If your transaction has 150 inputs, and each has 2 signatures, then there's 300 chances to hit that 1-in-512 "hole".  Thus probably half  transactions of that size would fail.  

Unfortunately, we can push a fix to the repo quickly but we can't do a new release that quickly.  I'll see if we can figure out a workaround that will get you unblocked.

**Comment by AndyOfiesh** [comment]
I think this finding confirms that breaking up the transaction into smaller pieces is a valid work around.

If you encounter this error, try sending about half as much of the transaction from the lockbox to itself. 

If you are unlucky enough to get the error multiple times just keep sending different sizes transactions from the lockbox to itself.

Repeating this process will drastically reduce the number of inputs in the lockbox, and thus the likelihood of hitting an unlucky bad signature.
