### ISSUE TITLE
Crash during rebuilding db

### ISSUE THREAD

**Issue by csillag** [etotheipi/BitcoinArmory#310]
I am running v0.93.2, which I have built from source.

This is what I get when I try to rebuild the database:

Command: `armory --rebuild  --debug`

Result:
```
Traceback (most recent call last):
  File "update_version.py", line 14, in <module>
    f = open(hash_loc, "r")
IOError: [Errno 2] No such file or directory: '.git/3cb2a80c7cd461ac26bf34f240a3b60e367'
(INFO) ArmoryUtils.py:1004 - Found existing databases dir; removing before rebuild
(INFO) ArmoryUtils.py:1076 - C++ block utilities loaded successfully
(INFO) ArmoryUtils.py:600 - Executing popen: free -m
(INFO) ArmoryUtils.py:600 - Executing popen: ['cat', '/proc/cpuinfo']
(INFO) ArmoryUtils.py:1186 - 
(INFO) ArmoryUtils.py:1187 - 
(INFO) ArmoryUtils.py:1188 - 
(INFO) ArmoryUtils.py:1189 - ************************************************************
(INFO) ArmoryUtils.py:1190 - Invoked: ArmoryQt.py --skip-online-check --rebuild --debug
(INFO) ArmoryUtils.py:1191 - ************************************************************
(INFO) ArmoryUtils.py:1192 - Loading Armory Engine:
(INFO) ArmoryUtils.py:1193 -    Armory Version        : 0.93.2
(INFO) ArmoryUtils.py:1194 -    Armory Build:         : None
(INFO) ArmoryUtils.py:1195 -    PyBtcWallet  Version  : 1.35
(INFO) ArmoryUtils.py:1196 - Detected Operating system: Linux
(INFO) ArmoryUtils.py:1197 -    OS Variant            : debian-8.1-
(INFO) ArmoryUtils.py:1198 -    User home-directory   : /home/csillag
(INFO) ArmoryUtils.py:1199 -    Satoshi BTC directory : /home/csillag/.bitcoin/
(INFO) ArmoryUtils.py:1200 -    Armory home dir       : /home/csillag/.armory/
(INFO) ArmoryUtils.py:1201 - Detected System Specs    : 
(INFO) ArmoryUtils.py:1202 -    Total Available RAM   : 7.79 GB
(INFO) ArmoryUtils.py:1203 -    CPU ID string         : Intel(R) Core(TM)2 Duo CPU     T9550  @ 2.66GHz
(INFO) ArmoryUtils.py:1204 -    Number of CPU cores   : 2 cores
(INFO) ArmoryUtils.py:1205 -    System is 64-bit      : True
(INFO) ArmoryUtils.py:1206 -    Preferred Encoding    : UTF-8
(INFO) ArmoryUtils.py:1207 -    Machine Arch          : x86_64
(INFO) ArmoryUtils.py:1208 -    Available HDD (ARM)   : 49 GB
(INFO) ArmoryUtils.py:1209 -    Available HDD (BTC)   : 49 GB
(INFO) ArmoryUtils.py:1210 - 
(INFO) ArmoryUtils.py:1211 - Network Name: Main Network
(INFO) ArmoryUtils.py:1212 - Satoshi Port: 8333
(INFO) ArmoryUtils.py:1213 - Do wlt check: True
(INFO) ArmoryUtils.py:1214 - Named options/arguments to armoryengine.py:
(INFO) ArmoryUtils.py:1216 -     nettimeout      : 2
(INFO) ArmoryUtils.py:1216 -     rescan          : False
(INFO) ArmoryUtils.py:1216 -     ignoreAllZC     : False
(INFO) ArmoryUtils.py:1216 -     enableSupernode : False
(INFO) ArmoryUtils.py:1216 -     disableModules  : False
(INFO) ArmoryUtils.py:1216 -     port            : None
(INFO) ArmoryUtils.py:1216 -     interport       : 8223
(INFO) ArmoryUtils.py:1216 -     skipStatsReport : False
(INFO) ArmoryUtils.py:1216 -     forceWalletCheck: False
(INFO) ArmoryUtils.py:1216 -     rebuild         : True
(INFO) ArmoryUtils.py:1216 -     datadir         : DEFAULT
(INFO) ArmoryUtils.py:1216 -     clearMempool    : False
(INFO) ArmoryUtils.py:1216 -     offline         : False
(INFO) ArmoryUtils.py:1216 -     coverageOutputDir: None
(INFO) ArmoryUtils.py:1216 -     armoryDBDir     : DEFAULT
(INFO) ArmoryUtils.py:1216 -     satoshiPort     : DEFAULT
(INFO) ArmoryUtils.py:1216 -     useTorSettings  : False
(INFO) ArmoryUtils.py:1216 -     netlog          : False
(INFO) ArmoryUtils.py:1216 -     keypool         : 100
(INFO) ArmoryUtils.py:1216 -     coverageInclude : None
(INFO) ArmoryUtils.py:1216 -     forceOnline     : True
(INFO) ArmoryUtils.py:1216 -     skipAnnounceCheck: False
(INFO) ArmoryUtils.py:1216 -     redownload      : False
(INFO) ArmoryUtils.py:1216 -     multisigFile    : DEFAULT
(INFO) ArmoryUtils.py:1216 -     disableTorrent  : False
(INFO) ArmoryUtils.py:1216 -     testAnnounceCode: False
(INFO) ArmoryUtils.py:1216 -     mtdebug         : False
(INFO) ArmoryUtils.py:1216 -     logDisable      : False
(INFO) ArmoryUtils.py:1216 -     settingsPath    : /home/csillag/.armory/ArmorySettings.txt
(INFO) ArmoryUtils.py:1216 -     verbosity       : None
(INFO) ArmoryUtils.py:1216 -     doDebug         : True
(INFO) ArmoryUtils.py:1216 -     enableDetSign   : True
(INFO) ArmoryUtils.py:1216 -     testnet         : False
(INFO) ArmoryUtils.py:1216 -     rpcport         : DEFAULT
(INFO) ArmoryUtils.py:1216 -     satoshiHome     : DEFAULT
(INFO) ArmoryUtils.py:1216 -     satoshiRpcport  : DEFAULT
(INFO) ArmoryUtils.py:1216 -     logFile         : /home/csillag/.armory/armorylog.txt
(INFO) ArmoryUtils.py:1216 -     disableConfPermis: False
(INFO) ArmoryUtils.py:1217 - Other arguments:
(INFO) ArmoryUtils.py:1220 - ************************************************************
(INFO) ArmoryUtils.py:1615 - C++ block utilities loaded successfully
(INFO) BDM.py:418 - Using the asynchronous/multi-threaded BlockDataManager.
(INFO) BDM.py:419 - Blockchain operations will happen in the background.  
(INFO) BDM.py:420 - Devs: check TheBDM.getState() before asking for data.
(INFO) BDM.py:421 - Registering addresses during rescans will queue them for 
(INFO) BDM.py:422 - inclusion after the current scan is completed.
(DEBUG) ArmoryQt.py:7076 - Checking for already open socket...
(INFO) ArmoryUtils.py:3521 - Using settings file: /home/csillag/.armory/ArmorySettings.txt
(INFO) announcefetch.py:95 - Reading files in fetcher directory:
(INFO) announcefetch.py:104 -    notify           : 78bbf86a93b31c391ad34ee1b26097abd9064c0c037a6d4a16d6d1cdb0c7635d
(INFO) announcefetch.py:104 -    changelog        : 791059d52f04d68a142730b421f46f52c3169440a168db50088fb2b7856e3d9b
(INFO) announcefetch.py:104 -    downloads        : 21707983b98ad85f3ac5fd50ec765c08a346d00eaddbeb117516d0b7c25c5dbf
(INFO) announcefetch.py:104 -    announce         : b8eec8ca1eb01c9c2a55690e5c779cdffa15b30a5ce611cc8444c43472d0ca98
(INFO) announcefetch.py:104 -    bootstrap        : b62c08932668ce162d51226135940724e90f4c71704ac936f74cc153b34cc251
(INFO) announcefetch.py:271 - Fetching: https://bitcoinarmory.com/announce.txt?osvar=debian&os=lin&ver=0.93.2&id=9bfc0ff1
(DEBUG) announcefetch.py:275 - Downloading URL: https://bitcoinarmory.com/announce.txt?osvar=debian&os=lin&ver=0.93.2&id=9bfc0ff1
(INFO) ArmoryQt.py:2735 - loadWalletsAndSettings
(INFO) ArmoryQt.py:2789 - Loading wallets...
(DEBUG) ArmoryUtils.py:1046 - /home/csillag/.armory/databases is a directory.
(DEBUG) ArmoryUtils.py:1046 - /home/csillag/.armory/atisignedannounce is a directory.
(INFO) ArmoryQt.py:2848 - Number of wallets read in: 3
(3 lines redacted here)
(INFO) ArmoryQt.py:2297 - Setting up networking...
(INFO) ArmoryQt.py:2326 - Internet status: 2
(INFO) ArmoryQt.py:2524 - loadBlockchainIfNecessary
(ERROR) ArmoryQt.py:1323 - 4 attempts to load blockchain failed.  Remove mempool.bin.
(ERROR) ArmoryQt.py:1328 - File mempool.bin does not exist. Nothing deleted.
(INFO) ArmoryQt.py:2545 - Setting netmode: 1
********************************************************************************
Loading Armory Engine:
   Armory Version:       0.93.2
   Armory Build:         None
   PyBtcWallet  Version: 1.35
Detected Operating system: Linux
   OS Variant            : ('debian', '8.1', '')
   User home-directory   : /home/csillag
   Satoshi BTC directory : /home/csillag/.bitcoin/
   Armory home dir       : /home/csillag/.armory/
   ArmoryDB directory     : /home/csillag/.armory/databases
   Armory settings file  : /home/csillag/.armory/ArmorySettings.txt
   Armory log file       : /home/csillag/.armory/armorylog.txt
   Do wallet checking    : True
-INFO  - 1440116585: (BlockUtils.cpp:894) blkfile dir: /home/csillag/.bitcoin/blocks
-INFO  - 1440116585: (BlockUtils.cpp:895) lmdb dir: /home/csillag/.armory/databases
-INFO  - 1440116585: (lmdb_wrapper.cpp:478) Opening databases...
(DEBUG) ArmoryQt.py:1411 - setupSystemTray
-INFO  - 1440116585: (BlockUtils.cpp:1244) Executing: doInitialSyncOnLoad_Rebuild
-WARN  - 1440116585: (BlockUtils.cpp:1213) Destroying databases;  will need to be rebuilt
-INFO  - 1440116585: (lmdb_wrapper.cpp:478) Opening databases...
(INFO) ArmoryQt.py:1514 - setupUriRegistration
(INFO) ArmoryUtils.py:600 - Executing popen: gconftool-2 --get /desktop/gnome/url-handlers/bitcoin/command
-INFO  - 1440116585: (BlockUtils.cpp:1297) Total number of blk*.dat files: 323
-INFO  - 1440116585: (BlockUtils.cpp:1298) Total blockchain bytes: 43,290,149,220
-INFO  - 1440116585: (BlockUtils.cpp:1671) Reading headers from db
-WARN  - 1440116585: (lmdb_wrapper.cpp:1478) No headers in DB yet!
-INFO  - 1440116585: (BlockUtils.cpp:1697) Found 1 headers in db
-DEBUG - 1440116585: (Blockchain.cpp:211) Organizing chain w/ rebuild
-WARN  - 1440116585: (BlockUtils.cpp:1327) --- Fetching SSH summaries for 344 registered addresses
-INFO  - 1440116585: (BlockUtils.cpp:1340) Left off at file 0, offset 0
-INFO  - 1440116585: (BlockUtils.cpp:1343) Reading headers and building chain...
-INFO  - 1440116585: (BlockUtils.cpp:1344) Starting at block file 0 offset 0
-INFO  - 1440116585: (BlockUtils.cpp:1346) Block height 0
(INFO) ArmoryUtils.py:600 - Executing popen: xdg-mime query default x-scheme-handler/bitcoin
(INFO) ArmoryUtils.py:600 - Executing popen: find /home/csillag -type f -name "mimeTypes.rdf"
(DEBUG) ArmoryQt.py:4361 - setupDashboard
(INFO) ArmoryQt.py:664 - Usermode: Advanced
(INFO) ArmoryQt.py:1809 - Changing usermode:
(INFO) ArmoryQt.py:1810 -    From: Advanced
(INFO) ArmoryQt.py:1818 -      To: Advanced
(INFO) ArmoryQt.py:6021 - Dashboard switched to "Scanning" mode
(INFO) Networking.py:65 - Connection initiated.  Start handshake
(INFO) ArmoryQt.py:6021 - Dashboard switched to "Scanning" mode
(INFO) Networking.py:156 - Received version message from peer:
(INFO) Networking.py:157 -    Version:     70002
(INFO) Networking.py:158 -    SubVersion:  /Satoshi:0.11.0/
(INFO) Networking.py:159 -    TimeStamp:   1440116556
(INFO) Networking.py:160 -    StartHeight: 370773
(INFO) Networking.py:350 - Handshake finished, connection open!
(ERROR) announcefetch.py:312 - Could not verify data in signed message block
Traceback (most recent call last):
  File "/mnt/user_data/home/csillag/local/lib/BitcoinArmory/announcefetch.py", line 304, in __runFetchSequence
    sig, msg = readSigBlock(digestData)
  File "/mnt/user_data/home/csillag/local/lib/BitcoinArmory/jasvet.py", line 589, in readSigBlock
    name = r.split(BEGIN_MARKER)[1].split(DASHX5)[0]
IndexError: list index out of range
-ERROR - 1440116590: (BlockUtils.cpp:639) Next block header found at offset 133243694
-ERROR - 1440116590: (BlockUtils.cpp:639) Next block header found at offset 71618184
-ERROR - 1440116590: (BlockUtils.cpp:639) Next block header found at offset 117617251
-DEBUG - 1440116591: (Blockchain.cpp:211) Organizing chain w/ rebuild
-INFO  - 1440116937: (BlockUtils.cpp:1381) Looking for first unrecognized block
bus error
```

And that's all.
Is that a known bug? If not, is this the right place to submit errors?
If yes, what further information should I submit? Thank you.

**Comment by droark** [comment]
Hello. The best way to handle this would be to open a support ticket via [the regular channels](https://support.bitcoinarmory.com/home). Thanks.
