### ISSUE TITLE
Error when sending lockbox TX

### ISSUE THREAD

**Issue by yuvadm** [etotheipi/BitcoinArmory#313]
```
2015-10-01 23:17 (ERROR) -- MultiSigDialogs.py:2139 - Error reading ASCII block
Traceback (most recent call last):
  File "/opt/BitcoinArmory/ui/MultiSigDialogs.py", line 2137, in clickedDone
    self.returnObj = self.importType().unserializeAscii(txt)
  File "/opt/BitcoinArmory/armoryengine/AsciiSerialize.py", line 75, in unserializeAscii
    raise UnserializeError('Unexpected BLKSTRING')
UnserializeError: Unexpected BLKSTRING
2015-10-01 23:21 (ERROR) -- Traceback (most recent call last):
  File "/opt/BitcoinArmory/ui/MultiSigDialogs.py", line 3108, in doBroadcast
    self.main.broadcastTransaction(finalTx, withOldSigWarning=False)
  File "/opt/BitcoinArmory/ArmoryQt.py", line 3726, in broadcastTransaction
    modified, newTx = pytx.minimizeDERSignaturePadding()
  File "/opt/BitcoinArmory/armoryengine/Transaction.py", line 720, in minimizeDERSignaturePadding
    paddingRemovedFromTxIn, newTxIn  = txIn.minimizeDERSignaturePadding()
  File "/opt/BitcoinArmory/armoryengine/Transaction.py", line 583, in minimizeDERSignaturePadding
    sigScript = createDERSigFromRS(rBin, sBin)
  File "/opt/BitcoinArmory/armoryengine/ArmoryUtils.py", line 2970, in createDERSigFromRS
    while sBin[0]=='\x00':
IndexError: string index out of range
```

Full log in ticket 1181 (why did you close it?)

**Comment by droark** [comment]
Try Armory 0.93.3 first, just in case. I know the code that's being cited was changed in 0.93.3 to support the "Low-S" signatures that are standard as of Core 0.11.1. It looks like your problem is different but I can't really comment on it.

**Comment by yuvadm** [comment]
I worked around this bug by creating many small TXs. Can't help reproduce anymore as all the funds have moved out.
