### ISSUE TITLE
TypeError in BlockDataManagerConig_blkFileLocation_set (2nd argument)

### ISSUE THREAD

**Issue by cookiengineer** [etotheipi/BitcoinArmory#319]
Hey,

Armory UI always tells it's offline, settings seem to work to initially sync with bitcoind in the background; but Armory itself has problems parsing that files (I think).

Versions affected: **Armory 0.93.3**
Systems affected: **Ubuntu 15.04 and UbuntuGNOME 15.10**

Callstack of the Error:

``` bash
Traceback (most recent call last):
  File "/usr/lib/armory/ArmoryQt.py", line 7057, in method_signal
    method()   
  File "/usr/lib/armory/ArmoryQt.py", line 2486, in proceedOnceBitcoindIsReady
    self.loadBlockchainIfNecessary()
  File "/usr/lib/armory/ArmoryQt.py", line 2538, in loadBlockchainIfNecessary
    TheBDM.goOnline()           
  File "/usr/lib/armory/armoryengine/BDM.py", line 148, in inner
    return func(*newArgs, **kwargs)
  File "/usr/lib/armory/armoryengine/BDM.py", line 251, in goOnline
    self.bdmThread.setConfig(self.bdmConfig())
  File "/usr/lib/armory/armoryengine/BDM.py", line 148, in inner
    return func(*newArgs, **kwargs)
  File "/usr/lib/armory/armoryengine/BDM.py", line 339, in bdmConfig
    bdmConfig.blkFileLocation = blockdir
  File "/usr/lib/armory/CppBlockUtils.py", line 2203, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlockDataManagerConfig, name, value)
  File "/usr/lib/armory/CppBlockUtils.py", line 51, in _swig_setattr
    return _swig_setattr_nondynamic(self,class_type,name,value,0)
  File "/usr/lib/armory/CppBlockUtils.py", line 44, in _swig_setattr_nondynamic
    if method: return method(self,value)
TypeError: in method 'BlockDataManagerConfig_blkFileLocation_set', argument 2 of type 'string const &'
```

**Comment by cookiengineer** [comment]
Closing this issue because this repo is unmaintained.
