### ISSUE TITLE
(ERROR) ArmoryUtils.pyc:3230 - Error in pybkgdthread: 'rpcuser'

### ISSUE THREAD

**Issue by fresheneesz** [etotheipi/BitcoinArmory#330]
I just installed the latest version of armory and ran it. This is what I get:

```
(ERROR) ArmoryUtils.pyc:3230 - Error in pybkgdthread: 'rpcuser'
Traceback (most recent call last):
  File "armoryengine\ArmoryUtils.pyc", line 3228, in run
  File "armoryengine\ArmoryUtils.pyc", line 3165, in funcPartial
  File "SDM.pyc", line 482, in pollBitcoindState
  File "SDM.pyc", line 696, in getSDMStateLogic
  File "SDM.pyc", line 834, in getTopBlockInfo
  File "SDM.pyc", line 826, in updateTopBlockInfo
  File "SDM.pyc", line 754, in createProxy
KeyError: 'rpcuser'
(ERROR) Traceback (most recent call last):
  File "ArmoryQt.py", line 6909, in <module>
  File "ArmoryQt.py", line 703, in __init__
  File "ArmoryQt.py", line 5324, in setDashboardDetails
  File "SDM.pyc", line 663, in getSDMState
  File "SDM.pyc", line 696, in getSDMStateLogic
  File "SDM.pyc", line 834, in getTopBlockInfo
  File "SDM.pyc", line 826, in updateTopBlockInfo
  File "SDM.pyc", line 754, in createProxy
KeyError: 'rpcuser'

Traceback (most recent call last):
  File "ArmoryQt.py", line 6909, in <module>
  File "ArmoryQt.py", line 703, in __init__
  File "ArmoryQt.py", line 5324, in setDashboardDetails
  File "SDM.pyc", line 663, in getSDMState
  File "SDM.pyc", line 696, in getSDMStateLogic
  File "SDM.pyc", line 834, in getTopBlockInfo
  File "SDM.pyc", line 826, in updateTopBlockInfo
  File "SDM.pyc", line 754, in createProxy
KeyError: 'rpcuser'
```

I'm on windows 8.1 running the latest armory_0.95.1_win64 . I haven't been able to successfully run armory for like a year. Wth guys?

I completely uninstalled Armory and reinstalled, same problem. I open the program, it immediately pops up a message that tells me to look in an error log file, which contains the above.

**Comment by achow101** [comment]
First of all, this is the wrong repo. Armory is being developed at https://github.com/goatpig/BitcoinArmory now, so please report issues there.

Open your bitcoin.conf file and remove any lines with `rpcuser` and `rpcpassword`. Then try again.
