### ISSUE TITLE
Crash when loading: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by WallyCZ** [etotheipi/BitcoinArmory#336]
Traceback (most recent call last):
  File "ArmoryQt.py", line 5929, in <module>
  File "ArmoryQt.py", line 244, in __init__
  File "ArmoryQt.py", line 2190, in loadWalletsAndSettings
  File "ArmoryQt.py", line 2196, in loadCppWallets
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 10: ordinal not in range(128)

**Comment by droark** [comment]
#341.
